import { NextResponse } from 'next/server';import type Stripe from 'stripe';import { stripe } from '@/lib/stripe';import { serviceClient } from '@/lib/supabase';import { plans,type Plan } from '@/config/pricing';import { serverTrack } from '@/lib/server-analytics';import { sendEmail } from '@/lib/emails';
export const runtime='nodejs';
export async function POST(req:Request){if(!process.env.STRIPE_WEBHOOK_SECRET||!process.env.SUPABASE_SERVICE_ROLE_KEY)return NextResponse.json({error:'Webhook not configured'},{status:503});const client=stripe();let event:Stripe.Event;try{event=client.webhooks.constructEvent(await req.text(),req.headers.get('stripe-signature')||'',process.env.STRIPE_WEBHOOK_SECRET)}catch{return NextResponse.json({error:'Invalid signature'},{status:400})}const db=serviceClient();const {data:seen,error:readError}=await db.from('stripe_events').select('id').eq('id',event.id).maybeSingle();if(readError)return NextResponse.json({error:'Database unavailable'},{status:500});if(seen)return NextResponse.json({received:true});try{
let id:string|undefined;
if(event.type==='checkout.session.completed'){const session=event.data.object as Stripe.Checkout.Session;id=typeof session.subscription==='string'?session.subscription:session.subscription?.id}
else if(event.type.startsWith('customer.subscription.'))id=(event.data.object as Stripe.Subscription).id;
if(id){const sub=await client.subscriptions.retrieve(id);const workspaceId=sub.metadata.workspace_id;if(!workspaceId)throw new Error('Missing workspace metadata');const customer=typeof sub.customer==='string'?sub.customer:sub.customer.id;const {data:current,error:loadError}=await db.from('subscriptions').select('stripe_customer_id,stripe_subscription_id,status').eq('workspace_id',workspaceId).single();if(loadError||!current||current.stripe_customer_id!==customer)throw new Error('Workspace customer mismatch');
const priceId=sub.items.data[0]?.price.id;const plan=(Object.keys(plans) as Plan[]).find(p=>process.env[plans[p].priceEnv]===priceId);if(!plan)throw new Error('Unknown subscription price');
// Read current Stripe state on every delivery; do not apply stale event payloads.
// Older canceled subscriptions cannot overwrite a newer subscription.
if(current.stripe_subscription_id&&current.stripe_subscription_id!==sub.id){const previous=await client.subscriptions.retrieve(current.stripe_subscription_id);if(['active','trialing','past_due','incomplete','unpaid'].includes(previous.status))throw new Error('Another subscription already exists');if(sub.status==='canceled'){const {error}=await db.from('stripe_events').insert({id:event.id});if(error&&error.code!=='23505')throw error;return NextResponse.json({received:true})}}
const periodEnd=Math.max(0,...sub.items.data.map(i=>i.current_period_end));const {error}=await db.from('subscriptions').update({stripe_subscription_id:sub.id,stripe_customer_id:customer,plan,status:sub.status,current_period_end:periodEnd?new Date(periodEnd*1000).toISOString():null,cancel_at_period_end:sub.cancel_at_period_end,max_active_requests:plans[plan].maxActive}).eq('workspace_id',workspaceId);if(error)throw error;
if(event.type==='checkout.session.completed'){await serverTrack('subscription_created',workspaceId,{plan});const c=await client.customers.retrieve(customer);if(!c.deleted&&c.email)await sendEmail(c.email,'Welcome','Your AIflow subscription is ready. Sign in to add your first request.')}
if(event.type==='customer.subscription.deleted'){const c=await client.customers.retrieve(customer);if(!c.deleted&&c.email)await sendEmail(c.email,'Subscription cancelled','Your subscription has ended. Previous deliverables remain available in your workspace.')}
}
const {error}=await db.from('stripe_events').insert({id:event.id});if(error&&error.code!=='23505')throw error;return NextResponse.json({received:true})
}catch(e){console.error('Stripe webhook reconciliation failed',e instanceof Error?e.message:'unknown');return NextResponse.json({error:'Webhook processing failed; retry required'},{status:500})}}
