'use server';
import { requireUser,requireAdmin } from '@/lib/auth';
import { revalidatePath } from 'next/cache';
import { serverTrack } from '@/lib/server-analytics';
import { sendEmail,type EmailEvent } from '@/lib/emails';
import { serviceClient } from '@/lib/supabase';
const text=(f:FormData,k:string,max=20000)=>String(f.get(k)||'').trim().slice(0,max);
function check(error:{message:string}|null){if(error)throw new Error(error.message)}
async function notify(requestId:string,event:EmailEvent){if(!process.env.SUPABASE_SERVICE_ROLE_KEY)return;try{const db=serviceClient();const {data:r}=await db.from('requests').select('title,workspace_id').eq('id',requestId).single();if(!r)return;const {data:w}=await db.from('workspaces').select('owner_id').eq('id',r.workspace_id).single();if(!w)return;const {data}=await db.auth.admin.getUserById(w.owner_id);if(data.user?.email)await sendEmail(data.user.email,event,`${event}: ${r.title}. Sign in to your workspace for details.`)}catch{console.error('Request notification failed',event)}}
export async function createRequest(form:FormData){const {db,user}=await requireUser();const {data:w,error:we}=await db.from('workspaces').select('id').eq('owner_id',user.id).single();check(we);if(!w)throw new Error('Workspace unavailable');const title=text(form,'title',160);if(!title)throw new Error('A title is required');const {data:id,error}=await db.rpc('add_request',{w:w.id,t:title,d:text(form,'description'),c:text(form,'category',80),p:text(form,'priority',10),s:text(form,'success',5000),l:text(form,'links',5000)});check(error);await serverTrack('request_created',user.id,{request_id:id});await notify(id,'New request received');revalidatePath('/dashboard');return id as string}
export async function editRequest(id:string,form:FormData){const {db}=await requireUser();const {error}=await db.rpc('edit_queued',{r:id,t:text(form,'title',160),d:text(form,'description'),c:text(form,'category',80),p:text(form,'priority',10),s:text(form,'success',5000),l:text(form,'links',5000)});check(error);revalidatePath('/dashboard')}
export async function deleteRequest(id:string){const {db}=await requireUser();const {error}=await db.rpc('delete_queued',{r:id});check(error);revalidatePath('/dashboard')}
export async function reorderQueue(workspaceId:string,ids:string[]){const {db}=await requireUser();const {error}=await db.rpc('reorder_queue',{w:workspaceId,ids});check(error);revalidatePath('/dashboard')}
export async function changeStatus(id:string,status:string){const {db,user}=await requireAdmin();if(!['queued','in_progress','completed'].includes(status))throw new Error('Invalid status');const {error}=await db.rpc('set_request_status',{r:id,s:status});check(error);if(status==='completed'){await serverTrack('request_completed',user.id,{request_id:id});await notify(id,'Request completed')}else if(status==='in_progress')await notify(id,'Request started');revalidatePath('/dashboard');revalidatePath('/admin')}
export async function addComment(id:string,body:string){const {db,user}=await requireUser();if(!body.trim()||body.length>10000)throw new Error('Write a comment under 10,000 characters');const {error}=await db.from('request_comments').insert({request_id:id,author_id:user.id,body:body.trim()});check(error);await notify(id,'New comment');revalidatePath('/dashboard')}
export async function uploadFile(id:string,form:FormData,deliverable=false){const {db,user}=deliverable?await requireAdmin():await requireUser();const {data:r}=await db.from('requests').select('id').eq('id',id).single();if(!r)throw new Error('Request not found');const file=form.get('file');if(!(file instanceof File)||!file.size)throw new Error('Choose a file');if(file.size>10*1024*1024)throw new Error('Maximum file size is 10 MB');const path=`${id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await db.storage.from('request-files').upload(path,file,{contentType:'application/octet-stream'});check(error);const {error:meta}=await db.from(deliverable?'deliverables':'request_files').insert(deliverable?{request_id:id,uploaded_by:user.id,title:file.name,path}:{request_id:id,uploaded_by:user.id,name:file.name,path});if(meta){throw new Error('File uploaded but metadata failed. Please retry: '+meta.message)}revalidatePath('/dashboard')}
export async function addDeliverable(id:string,url:string,title:string){const {db,user}=await requireAdmin();const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol))throw new Error('Use an HTTPS link');const {error}=await db.from('deliverables').insert({request_id:id,uploaded_by:user.id,title:title.trim().slice(0,160)||'Deliverable',url:parsed.href});check(error);revalidatePath('/dashboard')}
export async function fileLink(path:string){const {db}=await requireUser();const {data,error}=await db.storage.from('request-files').createSignedUrl(path,60);check(error);return data!.signedUrl}
export async function revision(id:string,note:string){const {db}=await requireUser();const {error}=await db.rpc('request_revision',{r:id,note});check(error);revalidatePath('/dashboard')}
export async function approve(id:string){const {db}=await requireUser();const {error}=await db.rpc('approve_deliverable',{d:id});check(error);revalidatePath('/dashboard')}
export async function adminMetadata(id:string,form:FormData){const {db}=await requireAdmin();const {error}=await db.from('requests').update({priority:text(form,'priority',10),complexity:text(form,'complexity',10),tags:text(form,'tags',500).split(',').map(x=>x.trim()).filter(Boolean)}).eq('id',id);check(error);revalidatePath('/admin');revalidatePath('/dashboard')}
export async function autoAdvance(id:string,enabled:boolean){const {db}=await requireAdmin();const {error}=await db.from('workspaces').update({auto_advance:enabled}).eq('id',id);check(error);revalidatePath('/admin')}
export async function startNext(id:string){const {db}=await requireAdmin();const {error}=await db.rpc('advance_workspace',{w:id});check(error);revalidatePath('/admin');revalidatePath('/dashboard')}
